### ISSUE TITLE
v1.6.6 breaks useragent in node (matrix-js-sdk)

### ISSUE THREAD

**Issue by Dogcatfee** [pimterry/loglevel#142]
While developing with matrix-js-sdk, loglevel throws errors about the useragent not being defined. Workarounds such as ```window.navigator={userAgent: 'node',}``` were tried before importing marix-js-sdk as well as in loglevel/lib/loglevel.js itself, however they did not fix the issue. This issue does not occur on v1.6.4.

``` bash
> babel-node index.js

/home/user/Applications/deckgui/node_modules/loglevel/lib/loglevel.js:23
        /Trident\/|MSIE /.test(window.navigator.userAgent)
                                                ^

TypeError: Cannot read property 'userAgent' of undefined
    at /home/user/Applications/deckgui/node_modules/loglevel/lib/loglevel.js:23:49
    at /home/user/Applications/deckgui/node_modules/loglevel/lib/loglevel.js:12:26
    at Object.<anonymous> (/home/user/Applications/deckgui/node_modules/loglevel/lib/loglevel.js:16:2)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Module._compile (/home/user/Applications/deckgui/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Object.newLoader [as .js] (/home/user/Applications/deckgui/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Function._module.default._load (/home/user/Applications/deckgui/node_modules/proton-native/bin/utils/requireImpl.js:23:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! calculator@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the calculator@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-01-29T03_24_43_762Z-debug.log
```

**Comment by pimterry** [comment]
So you're in node, but you have `window` defined globally? Interesting. Do you know why?

I think you might find that causes problems with a few other libraries too, since it's a pretty common pattern for detecting browser vs node environments.

That said, it'd be easy to handle this, so I'm very open to it. I'll try to put together a fix soon, and pull requests are very welcome in the meantime!

**Comment by pimterry** [comment]
v1.6.7 has now been published, including a fix for this case. That should solve the issue, but let me know if you have any other problems.
